spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8050

minio:
  url: http://localhost:9000
  access:
    key: URc2UUgycaYmivkKIVTC
    secret: cb7yz90x1eO9YmyODYoGXNwv2979Qr5XMsj9CMGe
  bucket:
    name: images