spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/project-x"
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
management:
  tracing:
    sampling:
      probability: 1.0